[workspace]
members = [
    "askama",
    "askama_axum",
    "askama_derive",
    "askama_escape",
    "askama_parser",
    "testing",
]

exclude = ["fuzz"]

resolver = "2"

default-members = [
    "askama",
    "askama_derive",
    "askama_escape",
    "askama_parser",
    "testing",
]
